services:
  edge-connector:
    build: .
    container_name: hospital-edge-connector
    restart: unless-stopped
    network_mode: "host"
    pid: "host"
    privileged: true
    volumes:
      - /var/ossec:/var/ossec
      - ./logs:/app/logs
      - ./index.ts:/app/index.ts
      - ./agent_version.txt:/app/agent_version.txt
      - /run/dbus:/run/dbus
      - /run/systemd:/run/systemd
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /dev/log:/dev/log
    env_file:
      - .env
